export const CATEGORIES = {
  N2_GRAMMAR: "上級I 文法 (N2)",
  N1_GRAMMAR: "上級II 文法 (N1 TRY!)",
  ELITE_ADVERBS: "会話 Elite Adverbs",
  CONNECTORS: "会話 Connectors",
  BUSINESS_VOCAB: "ビジネス語彙",
  N2_VERBS: "N2 動詞セット",
  CH01_VOCAB: "読解 CH.01 アリ",
  CH02_VOCAB: "読解 CH.02 血液型",
  CH04_VOCAB: "読解 CH.04 IT社会",
  CH05_VOCAB: "読解 CH.05 ゲーム",
  UNIT1_KANJI: "漢字 Unit 1",
  UNIT2_KANJI: "漢字 Unit 2",
  UNIT2_VOCAB: "Unit2 新出語彙",
  MY_WORDS: "My Saved Words 🗾",
};

export const SIM_GROUPS = {
  contrast: ["一方（いっぽう）","反面（はんめん）","～にしろ～にしろ","といっても"],
  tendency: ["がち","つつある","～げ"],
  condition: ["ないことには","ものなら","としたら","たとえ～ても","としても"],
  addition: ["上に（うえに）","に加えて","のみならず","なおかつ"],
  reason: ["ことから","～とあって","～だけあって","わけだ"],
  degree: ["極めて","少なからず","極端に（きょくたんに）","格段に（かくだんに）","頻繁に"],
  negative: ["黙殺（もくさつ）","無能（むのう）","怠惰（たいだ）","堕落（だらく）"],
  emotion: ["落胆（らくたん）","後ろめたい（うしろめたい）","もどかしい","浮かない顔（うかないかお）"],
  work: ["昇進する（しょうしんする）","不採用（ふさいよう）","中途採用（ちゅうとさいよう）","倒産する（とうさん）","朝礼（ちょうれい）"],
  social: ["人付き合い（ひとづきあい）","雑談（ざつだん）","内気な（うちきな）","上がり症（あがりしょう）","会釈（えしゃく）"],
  business: ["了承（りょうしょう）","承諾（しょうだく）","拒否（きょひ）","依頼（いらい）","要請（ようせい）","交渉（こうしょう）","調整（ちょうせい）","締結（ていけつ）"],
};

export const ALL_DATA = [
  // N2 GRAMMAR
  { jp: "～から見ると", en: "from the perspective of", heb: "מבחינת", cat: "N2_GRAMMAR", num: 60, conn: "N＋", ex: "外国人から見ると、日本のマナーは厳しい。", exHeb: "מנקודת מבט של זרים, הנימוסים ביפן מחמירים." },
  { jp: "～一方（いっぽう）", en: "on the other hand / while", heb: "מצד שני", cat: "N2_GRAMMAR", num: 61, conn: "普通形＋", ex: "便利な一方、高い。", exHeb: "נוח, אבל מצד שני יקר.", kanjiStory: "一(one) + 方(direction) = looking at one direction only" },
  { jp: "～ことから", en: "because of the fact that", heb: "בגלל ש", cat: "N2_GRAMMAR", num: 62, conn: "普通形＋", ex: "赤いことから、紅イモと呼ばれている。", exHeb: "בגלל שהוא אדום, הוא נקרא בטטה אדומה." },
  { jp: "～のみならず", en: "not only ~ but also", heb: "לא רק...אלא גם", cat: "N2_GRAMMAR", num: 63, conn: "普通形/N＋", ex: "若者のみならず大人も使っている。", exHeb: "לא רק צעירים אלא גם מבוגרים משתמשים בזה." },
  { jp: "～といった", en: "such as", heb: "כגון", cat: "N2_GRAMMAR", num: 64, conn: "N＋", ex: "寿司や天ぷらといった日本料理。", exHeb: "אוכל יפני כגון סושי וטמפורה." },
  { jp: "～にしたがって", en: "as ~ changes", heb: "ככל ש", cat: "N2_GRAMMAR", num: 65, conn: "V辞書形/N＋", ex: "年を取るにしたがって、体力が落ちる。", exHeb: "ככל שמזדקנים, הכוח הפיזי יורד." },
  { jp: "～得る/得ない（うる/えない）", en: "possible / impossible", heb: "אפשרי/בלתי אפשרי", cat: "N2_GRAMMAR", num: 66, conn: "Vます形＋", ex: "そんなことはあり得ない。", exHeb: "דבר כזה בלתי אפשרי.", kanjiStory: "得(gain) = something you can or cannot gain" },
  { jp: "～に反して", en: "contrary to", heb: "בניגוד ל", cat: "N2_GRAMMAR", num: 67, conn: "N＋", ex: "期待に反して、失敗した。", exHeb: "בניגוד לציפיות, נכשלתי." },
  { jp: "～に関して", en: "regarding", heb: "בנוגע ל", cat: "N2_GRAMMAR", num: 68, conn: "N＋", ex: "この問題に関して質問がある。", exHeb: "יש לי שאלה בנוגע לבעיה הזו." },
  { jp: "～反面（はんめん）", en: "on the flip side", heb: "מצד שני (הפוך)", cat: "N2_GRAMMAR", num: 69, conn: "普通形＋", ex: "便利な反面、危険もある。", exHeb: "נוח, אבל מצד שני גם מסוכן.", kanjiStory: "反(flip) + 面(face) = flipping to see the other face" },
  { jp: "～上（じょう）", en: "in terms of / from standpoint", heb: "מבחינת", cat: "N2_GRAMMAR", num: 70, conn: "N＋", ex: "健康上の理由で辞めた。", exHeb: "התפטרתי מסיבות בריאותיות." },
  { jp: "～つつある", en: "gradually ~ing (process of change)", heb: "בהדרגה (שינוי)", cat: "N2_GRAMMAR", num: 71, conn: "Vます形＋", ex: "状況が変わりつつある。", exHeb: "המצב משתנה בהדרגה." },
  { jp: "～ぶる", en: "pretend to be / act like", heb: "להעמיד פנים של", cat: "N2_GRAMMAR", num: 85, conn: "N/な形/い形＋", ex: "偉ぶるな。", exHeb: "אל תעמיד פנים שאתה חשוב." },
  { jp: "～に限って", en: "of all times / Murphy's law", heb: "דווקא כש", cat: "N2_GRAMMAR", num: 86, conn: "N＋", ex: "急いでいるときに限って電車が遅れる。", exHeb: "דווקא כשממהרים הרכבת מאחרת." },
  { jp: "～ことだ", en: "should / best to (advice)", heb: "כדאי ל", cat: "N2_GRAMMAR", num: 87, conn: "V辞書形/Vない形＋", ex: "もっと練習することだ。", exHeb: "צריך להתאמן יותר." },
  { jp: "～という＋N", en: "every single ~ (emphasis)", heb: "כל...בלי יוצא מן הכלל", cat: "N2_GRAMMAR", num: 88, conn: "N＋", ex: "木という木が燃えた。", exHeb: "כל עץ ועץ נשרף." },
  { jp: "～ところだった", en: "almost ~ (close call)", heb: "כמעט ש", cat: "N2_GRAMMAR", num: 89, conn: "V辞書形＋", ex: "遅刻するところだった。", exHeb: "כמעט איחרתי." },
  { jp: "～くらいなら", en: "rather than ~ (I'd prefer)", heb: "עדיף...מאשר", cat: "N2_GRAMMAR", num: 90, conn: "V辞書形＋", ex: "あの店に行くくらいなら自分で作る。", exHeb: "מאשר ללכת לחנות ההיא, עדיף להכין בעצמי." },
  { jp: "～まし（だ）", en: "better (lesser evil)", heb: "פחות גרוע", cat: "N2_GRAMMAR", num: 91, conn: "—", ex: "嘘よりましだ。", exHeb: "זה פחות גרוע משקר." },
  { jp: "～ものがある", en: "there's something ~ about it", heb: "יש משהו ב", cat: "N2_GRAMMAR", num: 92, conn: "普通形＋", ex: "心に響くものがある。", exHeb: "יש בזה משהו שנוגע ללב." },
  { jp: "～まい", en: "will probably never / refuses to", heb: "כנראה לא לעולם", cat: "N2_GRAMMAR", num: 93, conn: "V辞書形＋", ex: "二度と会うまい。", exHeb: "כנראה לא ניפגש שוב לעולם." },
  { jp: "～につけ", en: "whenever / every time (emotional)", heb: "כל פעם ש (רגשי)", cat: "N2_GRAMMAR", num: 94, conn: "V辞書形＋", ex: "ニュースを聞くにつけ不安になる。", exHeb: "כל פעם ששומעים חדשות, נהיה חרדה." },
  { jp: "～わりに（は）", en: "considering / for (unexpected)", heb: "בהתחשב ב (מפתיע)", cat: "N2_GRAMMAR", num: 95, conn: "普通形/N＋", ex: "年のわりに若く見える。", exHeb: "בהתחשב בגיל, הוא נראה צעיר." },
  { jp: "～うちに", en: "while / before it changes", heb: "כל עוד (לפני שישתנה)", cat: "N2_GRAMMAR", num: 96, conn: "V辞書形/Vない形＋", ex: "暗くならないうちに帰ろう。", exHeb: "בוא נחזור לפני שיחשיך." },
  { jp: "～げ", en: "seems ~ / has an air of ~", heb: "נראה כאילו", cat: "N2_GRAMMAR", num: 97, conn: "い形stem/な形＋", ex: "悲しげな顔。", exHeb: "פנים שנראות עצובות." },
  { jp: "～やら～やら", en: "things like ~ and ~ (overwhelmed)", heb: "דברים כמו...ו...", cat: "N2_GRAMMAR", num: 98, conn: "N/V辞書形＋", ex: "家賃やら交通費やら、お金がかかる。", exHeb: "שכירות, נסיעות, וכו' — עולה הרבה כסף." },
  { jp: "～かと思うと", en: "just when I thought ~ (sudden)", heb: "ברגע שחשבתי ש", cat: "N2_GRAMMAR", num: 99, conn: "Vた形＋", ex: "泣いたかと思うと笑い出した。", exHeb: "ברגע שחשבתי שהוא בוכה, הוא התחיל לצחוק." },
  { jp: "～にほかならない", en: "is none other than / precisely", heb: "אין זה אלא", cat: "N2_GRAMMAR", num: 100, conn: "N＋", ex: "努力の結果にほかならない。", exHeb: "זו אינה אלא תוצאה של מאמץ." },
  { jp: "～にすぎない", en: "merely / nothing more than", heb: "לא יותר מ", cat: "N2_GRAMMAR", num: 101, conn: "V辞書形/N＋", ex: "10人にすぎない。", exHeb: "לא יותר מעשרה אנשים." },
  { jp: "～上に（うえに）", en: "on top of that / in addition", heb: "בנוסף לכך", cat: "N2_GRAMMAR", num: 102, conn: "普通形＋", ex: "高い上に、まずい。", exHeb: "יקר, ובנוסף לכך לא טעים." },
  { jp: "～といっても", en: "even though I say (downplay)", heb: "אמנם...אבל", cat: "N2_GRAMMAR", num: 103, conn: "普通形＋", ex: "日本語ができるといっても、まだN2だ。", exHeb: "אמנם אני יודע יפנית, אבל עדיין N2." },
  { jp: "～に限る", en: "nothing beats / best option is", heb: "אין כמו", cat: "N2_GRAMMAR", num: 104, conn: "V辞書形/N＋", ex: "疲れたときはビールに限る。", exHeb: "כשעייפים אין כמו בירה." },
  { jp: "～だけあって", en: "as expected of / befitting", heb: "כצפוי מ", cat: "N2_GRAMMAR", num: 105, conn: "普通形/N＋", ex: "大阪だけあって、食べ物がうまい。", exHeb: "כצפוי מאוסקה, האוכל טעים." },
  { jp: "～にしろ～にしろ", en: "whether ~ or ~ (either way)", heb: "בין אם...ובין אם", cat: "N2_GRAMMAR", num: 106, conn: "普通形/N＋", ex: "賛成にしろ反対にしろ、理由を言え。", exHeb: "בין אם בעד ובין אם נגד, תגיד סיבה." },
  { jp: "～とか", en: "I heard that (hearsay)", heb: "שמעתי ש", cat: "N2_GRAMMAR", num: 107, conn: "普通形＋", ex: "中止だとか。", exHeb: "שמעתי שזה בוטל." },
  { jp: "～にそって", en: "in accordance with / along", heb: "בהתאם ל", cat: "N2_GRAMMAR", num: 108, conn: "N＋", ex: "マニュアルにそって行う。", exHeb: "לפעול בהתאם למדריך." },
  { jp: "～にかけては", en: "when it comes to (pride)", heb: "כשמדובר ב (גאווה)", cat: "N2_GRAMMAR", num: 109, conn: "N＋", ex: "料理にかけては誰にも負けない。", exHeb: "כשמדובר בבישול, אני לא מפסיד לאף אחד." },
  { jp: "～ないことには", en: "unless ~ (can't proceed)", heb: "אלא אם כן", cat: "N2_GRAMMAR", num: 110, conn: "Vない形＋", ex: "やってみないことには、わからない。", exHeb: "אם לא תנסה, לא תדע." },
  { jp: "～がち", en: "tend to (negative tendency)", heb: "נוטה ל (שלילי)", cat: "N2_GRAMMAR", num: 111, conn: "Vます形/N＋", ex: "忘れがちだ。", exHeb: "נוטה לשכוח." },
  { jp: "～つつ（も）", en: "although / while (contradiction)", heb: "למרות ש (סתירה)", cat: "N2_GRAMMAR", num: 112, conn: "Vます形＋", ex: "悪いと思いつつ、やめられない。", exHeb: "למרות שאני יודע שזה רע, אני לא יכול להפסיק." },
  { jp: "～としたら", en: "if we suppose / hypothetically", heb: "אם נניח ש", cat: "N2_GRAMMAR", num: 113, conn: "普通形＋", ex: "転職するとしたら、ITがいい。", exHeb: "אם הייתי מחליף עבודה, IT היה מתאים." },
  { jp: "～次第（しだい）", en: "depends on / as soon as", heb: "תלוי ב / ברגע ש", cat: "N2_GRAMMAR", num: 114, conn: "N/Vます形＋", ex: "努力次第だ。届き次第連絡します。", exHeb: "תלוי במאמץ. אצור קשר ברגע שזה יגיע.", kanjiStory: "次(next) + 第(order) = what comes next in order" },
  { jp: "～一方（だ）", en: "keeps ~ing only (one direction)", heb: "רק הולך ו", cat: "N2_GRAMMAR", num: 115, conn: "V辞書形＋", ex: "物価は上がる一方だ。", exHeb: "המחירים רק הולכים ועולים.", kanjiStory: "一(one) + 方(direction) = going in one direction only" },
  { jp: "～に先立って", en: "prior to / before (formal)", heb: "לפני (רשמי)", cat: "N2_GRAMMAR", num: 116, conn: "N＋", ex: "開店に先立って試食会が開かれた。", exHeb: "לפני הפתיחה נערך אירוע טעימות.", kanjiStory: "先(ahead) + 立(stand) = standing ahead of everyone" },
  { jp: "～上で（うえで）", en: "after doing / based on", heb: "לאחר ש / על בסיס", cat: "N2_GRAMMAR", num: 117, conn: "Vた形/Nの＋", ex: "相談した上で決める。", exHeb: "נחליט לאחר שנתייעץ." },
  { jp: "～にこたえて", en: "in response to (expectations)", heb: "בתגובה ל (ציפיות)", cat: "N2_GRAMMAR", num: 118, conn: "N＋", ex: "期待にこたえて頑張った。", exHeb: "השתדלתי בתגובה לציפיות." },
  { jp: "～ことにする", en: "decide to / pretend that", heb: "להחליט ל / להעמיד פנים", cat: "N2_GRAMMAR", num: 119, conn: "Vた形＋", ex: "聞かなかったことにする。", exHeb: "אעמיד פנים שלא שמעתי." },
  { jp: "～つもり", en: "believe mistakenly / thought I did", heb: "חושב בטעות ש", cat: "N2_GRAMMAR", num: 120, conn: "V辞書形/Vた形＋", ex: "送ったつもりだったが、送れていなかった。", exHeb: "חשבתי ששלחתי, אבל זה לא נשלח." },
  { jp: "～てならない", en: "can't help but feel (overwhelming)", heb: "לא יכול שלא להרגיש", cat: "N2_GRAMMAR", num: 121, conn: "Vて形/い形くて＋", ex: "不思議でならない。", exHeb: "לא יכול שלא להרגיש שזה מוזר." },
  { jp: "～ものなら", en: "if ~ could (challenge/warning)", heb: "אם אתה מסוגל...נסה", cat: "N2_GRAMMAR", num: 122, conn: "V可能形＋", ex: "できるものなら、やってみろ。", exHeb: "אם אתה מסוגל, נסה." },
  { jp: "～うか～まいか", en: "whether to ~ or not (agonizing)", heb: "אם ל...או לא (מתלבט)", cat: "N2_GRAMMAR", num: 123, conn: "V意向形＋か＋V辞書形＋まいか", ex: "行こうか行くまいか悩んでいる。", exHeb: "מתלבט אם ללכת או לא." },
  { jp: "～末に（すえに）", en: "after a long struggle/process", heb: "אחרי תהליך ארוך", cat: "N2_GRAMMAR", num: 124, conn: "Vた形/Nの＋", ex: "考えた末に、決めた。", exHeb: "אחרי מחשבה ארוכה, החלטתי.", kanjiStory: "末(end/tip) = reaching the very tip after a long journey" },
  { jp: "～たとえ～ても", en: "even if (strong determination)", heb: "גם אם (נחישות)", cat: "N2_GRAMMAR", num: 125, conn: "たとえ＋Vても＋", ex: "たとえ難しくても、あきらめない。", exHeb: "גם אם קשה, לא אוותר." },
  { jp: "～がたい", en: "hard to / difficult to (emotionally)", heb: "קשה ל (רגשית)", cat: "N2_GRAMMAR", num: 126, conn: "Vます形＋", ex: "受け入れがたい。", exHeb: "קשה לקבל את זה." },
  { jp: "～もかまわず", en: "regardless of / not caring about", heb: "בלי להתחשב ב", cat: "N2_GRAMMAR", num: 127, conn: "N＋", ex: "人目もかまわず泣いた。", exHeb: "בכה בלי להתחשב במבטי אנשים." },
  { jp: "～あまり（に）", en: "so much ~ that (excess → result)", heb: "כל כך...עד ש", cat: "N2_GRAMMAR", num: 128, conn: "V辞書形/な形な＋", ex: "心配するあまり痩せた。", exHeb: "דאג כל כך עד שרזה." },
  { jp: "～を込めて", en: "with (feeling/soul) put into", heb: "עם רגש מושקע", cat: "N2_GRAMMAR", num: 129, conn: "N＋", ex: "心を込めて作った。", exHeb: "הכנתי עם כל הלב." },
  { jp: "～も～ば～も", en: "both ~ and ~ (balance)", heb: "גם...וגם (איזון)", cat: "N2_GRAMMAR", num: 130, conn: "N＋も＋V条件形＋N＋も", ex: "いいときもあれば悪いときもある。", exHeb: "יש זמנים טובים וגם זמנים רעים." },
  { jp: "～ぬく", en: "do thoroughly / endure to the end", heb: "עד הסוף (סבל)", cat: "N2_GRAMMAR", num: 131, conn: "Vます形＋", ex: "最後まで走りぬいた。", exHeb: "רצתי עד הסוף." },
  { jp: "～ものだ", en: "used to ~ (nostalgia for past)", heb: "פעם הייתי (נוסטלגיה)", cat: "N2_GRAMMAR", num: 132, conn: "普通形（過去）＋", ex: "昔はよく遊んだものだ。", exHeb: "פעם הייתי משחק הרבה." },
  { jp: "～をめぐって", en: "concerning / over (dispute)", heb: "סביב הנושא של (מחלוקת)", cat: "N2_GRAMMAR", num: 133, conn: "N＋", ex: "教育問題をめぐって議論した。", exHeb: "התנהל ויכוח סביב נושאי חינוך." },
  { jp: "～わけだ", en: "no wonder / so that's why", heb: "לא פלא ש / אז ככה", cat: "N2_GRAMMAR", num: 134, conn: "普通形＋", ex: "毎日練習した。上手になったわけだ。", exHeb: "התאמן כל יום. לא פלא שהשתפר." },
  { jp: "～にあたって", en: "on the occasion of (formal)", heb: "לרגל (רשמי)", cat: "N2_GRAMMAR", num: 135, conn: "V辞書形/N＋", ex: "卒業にあたって、一言あいさつします。", exHeb: "לרגל הסיום, אומר כמה מילים." },
  { jp: "～に加えて", en: "in addition to", heb: "בנוסף ל", cat: "N2_GRAMMAR", num: 136, conn: "N＋", ex: "経験に加えて、語学力も必要だ。", exHeb: "בנוסף לניסיון, צריך גם יכולת שפה." },
  { jp: "～としても", en: "even if (hypothetical, still won't)", heb: "גם אם (היפותטי)", cat: "N2_GRAMMAR", num: 137, conn: "V/A＋", ex: "合格したとしても、安心できない。", exHeb: "גם אם אעבור, אי אפשר להירגע." },
  // N1 GRAMMAR
  { jp: "～を皮切りに（かわきりに）", en: "starting with ~ then expanding", heb: "החל מ (ואז התרחב)", cat: "N1_GRAMMAR", num: 1, conn: "N/Vた+の＋", ex: "1974年を皮切りに全国に出店した。", exHeb: "החל מ-1974 פתחו סניפים בכל הארץ.", kanjiStory: "皮(skin) + 切(cut) = the first surgical cut → starting point" },
  { jp: "～とあって", en: "given that (special → obvious result)", heb: "בהתחשב ש (מיוחד→תוצאה)", cat: "N1_GRAMMAR", num: 2, conn: "普通形＋", ex: "人気バンドが来ているとあって、ファンが集まった。", exHeb: "בהתחשב שלהקה פופולרית הגיעה, אוהדים התאספו." },
  { jp: "～ならではの", en: "unique to ~ / only ~ can offer", heb: "ייחודי ל (רק ל~ יש)", cat: "N1_GRAMMAR", num: 3, conn: "N＋ならではの＋N", ex: "海水浴は夏ならではのものだ。", exHeb: "שחייה בים זה דבר ייחודי לקיץ." },
  { jp: "～に至っては（にいたっては）", en: "among a bad group, THIS one is the worst", heb: "בין כולם, דווקא...הכי גרוע", cat: "N1_GRAMMAR", num: 7, conn: "N＋に至っては", ex: "兄弟は全員成績が悪いが、弟に至っては赤点ばかりだ。", exHeb: "כל האחים עם ציונים גרועים, אבל הצעיר — רק ציונים נכשלים.", kanjiStory: "至(reach) + っては = reaching the extreme point → THIS one is the worst" },
  { jp: "～といえども", en: "even X can't escape / even if ~", heb: "אפילו...לא יכול לחמוק", cat: "N1_GRAMMAR", num: 8, conn: "N＋といえども", ex: "社長といえども、法律には逆らえない。", exHeb: "אפילו המנכ\"ל לא יכול לחמוק מהחוק." },
  { jp: "～を余儀なくされる（よぎなくされる）", en: "forced to do something (victim)", heb: "נאלץ ל (קורבן)", cat: "N1_GRAMMAR", num: 9, conn: "N＋を余儀なくされる", ex: "台風で避難を余儀なくされた。", exHeb: "נאלצתי לפנות בגלל הטייפון.", kanjiStory: "余(surplus) + 儀(ceremony) = no surplus of options → forced" },
  { jp: "～たりとも…ない", en: "not even ONE, absolute zero", heb: "אפילו לא אחד, אפס מוחלט", cat: "N1_GRAMMAR", num: 10, conn: "1＋助数詞＋たりとも…ない", ex: "一秒たりとも無駄にしたくない。", exHeb: "לא רוצה לבזבז אפילו שנייה אחת." },
  { jp: "～きらいがある", en: "has an undesirable tendency", heb: "יש נטייה בעייתית ל", cat: "N1_GRAMMAR", num: 11, conn: "Vる/Vない＋きらいがある", ex: "彼は人の話を聞かないきらいがある。", exHeb: "יש לו נטייה בעייתית לא להקשיב לאחרים." },
  { jp: "～次第だ（N1）", en: "here's the reason (formal/business)", heb: "וזו הסיבה (רשמי/עסקי)", cat: "N1_GRAMMAR", num: 12, conn: "V普通形＋次第だ", ex: "ご連絡が遅れた次第です。", exHeb: "וזו הסיבה שהתגובה התעכבה.", kanjiStory: "次(next) + 第(order) = explaining the order of events" },
  // ELITE ADVERBS
  { jp: "そもそも", en: "in the first place (questioning fundamentals)", heb: "מלכתחילה", cat: "ELITE_ADVERBS", ex: "そもそも、何が原因なのか。", exHeb: "מלכתחילה, מה הסיבה?" },
  { jp: "あえて", en: "dare to / deliberately choosing to", heb: "להעז / בכוונה", cat: "ELITE_ADVERBS", ex: "あえて言うなら、それは間違いだ。", exHeb: "אם להעז ולומר, זו טעות." },
  { jp: "いわば", en: "so to speak / metaphorically", heb: "כביכול / באופן מטאפורי", cat: "ELITE_ADVERBS", ex: "教育はいわば未来への投資だ。", exHeb: "חינוך הוא כביכול השקעה בעתיד." },
  { jp: "果たして（はたして）", en: "I wonder if really (doubt)", heb: "האם באמת (ספק)", cat: "ELITE_ADVERBS", ex: "果たして、それは正しいのだろうか。", exHeb: "האם באמת זה נכון?", kanjiStory: "果(fruit) = did it really bear fruit? → I wonder if really" },
  { jp: "少なからず（すくなからず）", en: "to no small extent / considerably", heb: "לא מעט / במידה ניכרת", cat: "ELITE_ADVERBS", ex: "社会に少なからず影響がある。", exHeb: "יש השפעה לא מבוטלת על החברה.", kanjiStory: "少(few) + ず(not) = not few → to no small extent" },
  { jp: "とりわけ", en: "especially / in particular", heb: "בעיקר / במיוחד", cat: "ELITE_ADVERBS", ex: "とりわけ食文化に興味がある。", exHeb: "יש לי עניין במיוחד בתרבות האוכל." },
  // 極めて moved to MY_WORDS
  { jp: "むしろ", en: "rather / if anything (flipping)", heb: "יותר נכון / אדרבא", cat: "ELITE_ADVERBS", ex: "むしろ、逆だと思う。", exHeb: "אדרבא, אני חושב שזה הפוך." },
  // 頻繁に moved to MY_WORDS
  // CONNECTORS
  { jp: "なぜなら～からです", en: "because (formal reason-giving)", heb: "כי (רשמי)", cat: "CONNECTORS", ex: "なぜなら、食べ物がおいしいからです。", exHeb: "כי האוכל טעים." },
  { jp: "確かに～しかし", en: "true, but... (counter-argument)", heb: "נכון, אבל... (טיעון נגדי)", cat: "CONNECTORS", ex: "確かにそうだけど、私は反対だ。", exHeb: "נכון, אבל אני נגד." },
  { jp: "しかしながら", en: "however (more elegant than しかし)", heb: "אולם (אלגנטי)", cat: "CONNECTORS", ex: "しかしながら、リスクもある。", exHeb: "אולם, יש גם סיכונים." },
  { jp: "なおかつ（尚且つ）", en: "furthermore / and on top of that", heb: "ויתרה מכך", cat: "CONNECTORS", ex: "安い、なおかつ品質もいい。", exHeb: "זול, ויתרה מכך גם איכותי." },
  // BUSINESS
  { jp: "了承（りょうしょう）", en: "acceptance / acknowledgment", heb: "אישור / קבלה", cat: "BUSINESS_VOCAB", ex: "ご了承ください。", exHeb: "אנא קבלו זאת.", kanjiStory: "了(finish) + 承(receive) = received and done" },
  { jp: "承諾（しょうだく）", en: "consent / agreement", heb: "הסכמה", cat: "BUSINESS_VOCAB", ex: "承諾を得る。", exHeb: "לקבל הסכמה.", kanjiStory: "承(receive) + 諾(agree) = received and agreed" },
  { jp: "拒否（きょひ）", en: "refusal / rejection", heb: "סירוב", cat: "BUSINESS_VOCAB", ex: "要求を拒否する。", exHeb: "לסרב לדרישה.", kanjiStory: "拒(refuse) + 否(deny) = refuse and deny" },
  { jp: "依頼（いらい）", en: "request (formal)", heb: "בקשה (רשמית)", cat: "BUSINESS_VOCAB", ex: "仕事を依頼する。", exHeb: "לבקש עבודה באופן רשמי.", kanjiStory: "依(rely) + 頼(ask) = rely on someone by asking" },
  { jp: "要請（ようせい）", en: "formal demand / strong request", heb: "דרישה רשמית", cat: "BUSINESS_VOCAB", ex: "政府に要請する。", exHeb: "לדרוש מהממשלה.", kanjiStory: "要(need) + 請(request) = needed request" },
  { jp: "交渉（こうしょう）", en: "negotiation", heb: "משא ומתן", cat: "BUSINESS_VOCAB", ex: "給料について交渉する。", exHeb: "לנהל משא ומתן על המשכורת.", kanjiStory: "交(exchange) + 渉(wade) = wading through exchange" },
  { jp: "調整（ちょうせい）", en: "adjustment / coordination", heb: "התאמה / תיאום", cat: "BUSINESS_VOCAB", ex: "スケジュールを調整する。", exHeb: "לתאם את לוח הזמנים.", kanjiStory: "調(tune) + 整(arrange) = tune and arrange" },
  { jp: "締結（ていけつ）", en: "contract conclusion / signing", heb: "חתימת חוזה", cat: "BUSINESS_VOCAB", ex: "契約を締結する。", exHeb: "לחתום על חוזה.", kanjiStory: "締(tie) + 結(bind) = tied and bound" },
  { jp: "契機（けいき）", en: "trigger / turning point", heb: "נקודת מפנה", cat: "BUSINESS_VOCAB", ex: "これを契機に改善する。", exHeb: "לשפר בעקבות זה.", kanjiStory: "契(promise) + 機(opportunity) = moment of commitment" },
  // N2 VERBS
  { jp: "収める（おさめる）", en: "to obtain / achieve results", heb: "להשיג תוצאות", cat: "N2_VERBS", ex: "成果を収める。", exHeb: "להשיג תוצאות.", kanjiStory: "収(harvest) = harvesting results" },
  { jp: "補う（おぎなう）", en: "to supplement / compensate for", heb: "להשלים / לפצות", cat: "N2_VERBS", ex: "不足を補う。", exHeb: "להשלים את החסר.", kanjiStory: "補(patch) = patching up what's missing" },
  { jp: "及ぼす（およぼす）", en: "to exert / cause (influence)", heb: "להשפיע / לגרום", cat: "N2_VERBS", ex: "影響を及ぼす。", exHeb: "להפעיל השפעה.", kanjiStory: "及(reach) = reaching influence outward" },
  { jp: "妨げる（さまたげる）", en: "to obstruct / hinder", heb: "לעכב / למנוע", cat: "N2_VERBS", ex: "成長を妨げる。", exHeb: "לעכב את הצמיחה.", kanjiStory: "妨(hinder) = a barrier blocking the way" },
  { jp: "蓄える（たくわえる）", en: "to store / accumulate", heb: "לאגור / לצבור", cat: "N2_VERBS", ex: "知識を蓄える。", exHeb: "לצבור ידע.", kanjiStory: "蓄(store) = storing up reserves for later" },
  { jp: "費やす（ついやす）", en: "to spend / consume (time/money)", heb: "להוציא (זמן/כסף)", cat: "N2_VERBS", ex: "時間を費やす。", exHeb: "להוציא זמן.", kanjiStory: "費(expense) = spending away resources" },
  { jp: "捉える（とらえる）", en: "to grasp / seize / perceive", heb: "לתפוס / לקלוט", cat: "N2_VERBS", ex: "チャンスを捉える。", exHeb: "לתפוס הזדמנות.", kanjiStory: "捉(catch) = catching and grasping tight" },
  { jp: "養う（やしなう）", en: "to foster / nurture / develop", heb: "לטפח / לפתח", cat: "N2_VERBS", ex: "考える力を養う。", exHeb: "לטפח כושר חשיבה.", kanjiStory: "養(nurture) = feeding to help grow" },
  { jp: "避ける（よける）", en: "to dodge / avoid", heb: "להימנע / להתחמק", cat: "N2_VERBS", ex: "危険を避ける。", exHeb: "להימנע מסכנה.", kanjiStory: "避(avoid) = stepping aside to dodge" },
  { jp: "改める（あらためる）", en: "to renew / correct / reform", heb: "לתקן / לחדש", cat: "N2_VERBS", ex: "態度を改める。", exHeb: "לתקן את הגישה.", kanjiStory: "改(reform) = breaking old to make new" },
  { jp: "怠る（おこたる）", en: "to neglect / be negligent", heb: "להזניח", cat: "N2_VERBS", ex: "準備を怠る。", exHeb: "להזניח את ההכנות.", kanjiStory: "怠(lazy) = heart neglecting its duties" },
  { jp: "重んじる（おもんじる）", en: "to value / honor / respect", heb: "להעריך / לכבד", cat: "N2_VERBS", ex: "礼儀を重んじる。", exHeb: "לכבד נימוסים.", kanjiStory: "重(heavy) = treating something as heavy → important" },
  { jp: "逆らう（さからう）", en: "to go against / defy", heb: "להתנגד / למרוד", cat: "N2_VERBS", ex: "親に逆らう。", exHeb: "למרוד בהורים.", kanjiStory: "逆(reverse) = going the reverse way" },
  // CH01
  { jp: "落胆（らくたん）", en: "discouraged / dejected", heb: "מאוכזב / מדוכא", cat: "CH01_VOCAB", ex: "結果を聞いて落胆した。", exHeb: "שמעתי את התוצאות והתאכזבתי.", kanjiStory: "落(fall) + 胆(guts) = your guts fall out" },
  { jp: "慨嘆（がいたん）する", en: "to lament / sigh deeply", heb: "להתאונן / לגנוח", cat: "CH01_VOCAB", ex: "世の中の変化を慨嘆する。", exHeb: "מתאונן על השינויים בעולם.", kanjiStory: "慨(lament) + 嘆(sigh) = lament and sigh" },
  { jp: "堕落（だらく）", en: "moral decay / degeneration", heb: "התדרדרות מוסרית", cat: "CH01_VOCAB", ex: "堕落した生活。", exHeb: "חיים של התדרדרות מוסרית.", kanjiStory: "堕(fall) + 落(drop) = falling and dropping" },
  { jp: "説得（せっとく）する", en: "to persuade / convince", heb: "לשכנע", cat: "CH01_VOCAB", ex: "母を説得して日本に来た。", exHeb: "שכנעתי את אמא ובאתי ליפן.", kanjiStory: "説(explain) + 得(gain) = explain until you gain agreement" },
  { jp: "崩壊（ほうかい）する", en: "to collapse / crumble", heb: "להתמוטט", cat: "CH01_VOCAB", ex: "建物が崩壊した。", exHeb: "הבניין התמוטט.", kanjiStory: "崩(crumble) + 壊(break) = crumbles and breaks" },
  { jp: "潜む（ひそむ）", en: "to lurk / be concealed", heb: "להסתתר / לארוב", cat: "CH01_VOCAB", ex: "危険が潜んでいる。", exHeb: "סכנה אורבת.", kanjiStory: "潜(submerge) = lurking beneath the surface" },
  { jp: "巧妙（こうみょう）さ", en: "cleverness / ingenuity", heb: "פיקחות / תחכום", cat: "CH01_VOCAB", ex: "巧妙なトリック。", exHeb: "טריק מתוחכם.", kanjiStory: "巧(skillful) + 妙(mysterious) = skillfully mysterious" },
  { jp: "識別（しきべつ）する", en: "to distinguish / identify", heb: "להבחין / לזהות", cat: "CH01_VOCAB", ex: "本物と偽物を識別する。", exHeb: "להבחין בין אמיתי למזויף.", kanjiStory: "識(recognize) + 別(separate) = recognize the difference" },
  // CH02
  { jp: "大ざっぱ", en: "rough / careless / sloppy", heb: "מרושל / לא מדויק", cat: "CH02_VOCAB", ex: "彼の仕事は大ざっぱだ。", exHeb: "העבודה שלו מרושלת." },
  { jp: "こだわり", en: "obsession / insistence on quality", heb: "קפדנות / אובססיה", cat: "CH02_VOCAB", ex: "コーヒーにこだわりがある。", exHeb: "יש לי קפדנות לגבי קפה." },
  { jp: "根拠（こんきょ）", en: "basis / grounds / evidence", heb: "בסיס / ראיה", cat: "CH02_VOCAB", ex: "科学的な根拠がない。", exHeb: "אין בסיס מדעי.", kanjiStory: "根(root) + 拠(base) = the root base" },
  { jp: "強固（きょうこ）", en: "firm / solid / unyielding", heb: "איתן / מוצק", cat: "CH02_VOCAB", ex: "強固な信念を持つ。", exHeb: "להחזיק באמונה איתנה.", kanjiStory: "強(strong) + 固(hard) = strong and hard" },
  { jp: "根深い（ねぶかい）", en: "deep-rooted / entrenched", heb: "מושרש עמוק", cat: "CH02_VOCAB", ex: "根深い問題だ。", exHeb: "זו בעיה מושרשת עמוק.", kanjiStory: "根(root) + 深(deep) = roots go deep" },
  { jp: "究極（きゅうきょく）", en: "ultimate / final / supreme", heb: "אולטימטיבי / עליון", cat: "CH02_VOCAB", ex: "究極の選択。", exHeb: "הבחירה האולטימטיבית.", kanjiStory: "究(investigate) + 極(extreme) = investigate to the extreme" },
  // CH04
  // 没入する moved to MY_WORDS
  { jp: "本質（ほんしつ）", en: "essence / true nature / core", heb: "מהות / טבע אמיתי", cat: "CH04_VOCAB", ex: "問題の本質を考える。", exHeb: "לחשוב על מהות הבעיה.", kanjiStory: "本(true) + 質(nature) = true nature" },
  { jp: "把握する（はあく）", en: "to grasp / comprehend fully", heb: "לתפוס / להבין לעומק", cat: "CH04_VOCAB", ex: "状況を把握する。", exHeb: "לתפוס את המצב.", kanjiStory: "把(grip) + 握(squeeze) = grip and squeeze" },
  { jp: "陥る（おちいる）", en: "to fall into (bad state)", heb: "ליפול ל (מצב רע)", cat: "CH04_VOCAB", ex: "パニックに陥る。", exHeb: "ליפול לפניקה.", kanjiStory: "陥(pit) = falling into a hidden pit" },
  { jp: "格段に（かくだんに）", en: "dramatically / remarkably", heb: "בצורה דרמטית", cat: "CH04_VOCAB", ex: "格段に良くなった。", exHeb: "השתפר בצורה דרמטית.", kanjiStory: "格(rank) + 段(step) = a rank and step above" },
  { jp: "向上する（こうじょう）", en: "to improve / advance", heb: "להשתפר / להתקדם", cat: "CH04_VOCAB", ex: "日本語力が向上した。", exHeb: "היפנית שלי השתפרה.", kanjiStory: "向(face) + 上(up) = facing upward" },
  // CH05
  { jp: "導入（どうにゅう）", en: "introduction / implementation", heb: "הטמעה / הכנסה", cat: "CH05_VOCAB", ex: "新しいシステムを導入する。", exHeb: "להטמיע מערכת חדשה.", kanjiStory: "導(guide) + 入(enter) = guide it in" },
  { jp: "戸惑い（とまどい）", en: "bewilderment / confusion", heb: "מבוכה / בלבול", cat: "CH05_VOCAB", ex: "戸惑いを感じた。", exHeb: "הרגשתי מבוכה.", kanjiStory: "戸(door) + 惑(confused) = confused at the door" },
  { jp: "成果（せいか）", en: "achievement / fruit of effort", heb: "תוצאות / פרי מאמץ", cat: "CH05_VOCAB", ex: "努力の成果が出た。", exHeb: "התוצאות של המאמץ נראו.", kanjiStory: "成(become) + 果(fruit) = became fruit" },
  { jp: "もたらす", en: "to bring about / cause / produce", heb: "לגרום / להביא", cat: "CH05_VOCAB", ex: "大きな変化をもたらした。", exHeb: "גרם לשינוי גדול." },
  // UNIT1 KANJI
  { jp: "積極的（せっきょくてき）", en: "proactive / assertive", heb: "פרואקטיבי / אקטיבי", cat: "UNIT1_KANJI", ex: "積極的に参加する。", exHeb: "להשתתף באופן פעיל.", kanjiStory: "積(pile) + 極(extreme) = piling up to the extreme" },
  { jp: "被害（ひがい）", en: "damage / harm / victimization", heb: "נזק / פגיעה", cat: "UNIT1_KANJI", ex: "台風の被害。", exHeb: "נזקי הטייפון.", kanjiStory: "被(receive) + 害(harm) = receiving harm" },
  { jp: "頑固（がんこ）", en: "stubborn / obstinate", heb: "עקשן", cat: "UNIT1_KANJI", ex: "頑固な人。", exHeb: "אדם עקשן.", kanjiStory: "頑(stubborn) + 固(hard) = stubbornly hard" },
  { jp: "普及する（ふきゅうする）", en: "to spread widely / become common", heb: "להתפשט / להפוך לנפוץ", cat: "UNIT1_KANJI", ex: "スマホが普及した。", exHeb: "הסמארטפונים התפשטו.", kanjiStory: "普(universal) + 及(reach) = reaching everywhere" },
  { jp: "不況（ふきょう）", en: "recession / economic downturn", heb: "מיתון כלכלי", cat: "UNIT1_KANJI", ex: "経済の不況。", exHeb: "מיתון כלכלי.", kanjiStory: "不(not) + 況(condition) = conditions not good" },
  { jp: "昇進する（しょうしんする）", en: "to be promoted (at work)", heb: "לקבל קידום", cat: "UNIT1_KANJI", ex: "部長に昇進した。", exHeb: "קודם למנהל מחלקה.", kanjiStory: "昇(rise) + 進(advance) = rising and advancing" },
  { jp: "自己開示（じこかいじ）", en: "self-disclosure / opening up", heb: "חשיפה עצמית", cat: "UNIT1_KANJI", ex: "自己開示が大切だ。", exHeb: "חשיפה עצמית חשובה.", kanjiStory: "自(self) + 己(oneself) + 開(open) + 示(show) = open and show yourself" },
  { jp: "抱く（いだく）", en: "to harbor (feelings) / hold", heb: "לחוש / לטפח (רגש)", cat: "UNIT1_KANJI", ex: "夢を抱く。", exHeb: "לחלום חלום.", kanjiStory: "抱(embrace) = wrapping arms around feelings" },
  { jp: "勲章（くんしょう）", en: "medal of honor / decoration", heb: "מדליית כבוד / אות הצטיינות", cat: "UNIT1_KANJI", ex: "勲章を受ける。", exHeb: "לקבל מדליית כבוד.", kanjiStory: "勲(merit) + 章(badge) = badge of merit" },
  // UNIT2 KANJI
  { jp: "布（ぬの）", en: "cloth / fabric", heb: "בד / אריג", cat: "UNIT2_KANJI", ex: "この布は柔らかい。", exHeb: "הבד הזה רך.", kanjiStory: "布(cloth) = fabric spread out wide" },
  { jp: "配布（はいふ）", en: "distribution / handing out", heb: "הפצה / חלוקה", cat: "UNIT2_KANJI", ex: "資料を配布する。", exHeb: "לחלק חומרים.", kanjiStory: "配(distribute) + 布(spread) = distribute and spread" },
  { jp: "分布（ぶんぷ）", en: "distribution / spread (geographical)", heb: "התפלגות / פיזור", cat: "UNIT2_KANJI", ex: "人口の分布を調べる。", exHeb: "לחקור את התפלגות האוכלוסייה.", kanjiStory: "分(divide) + 布(spread) = divided spread across an area" },
  { jp: "従う（したがう）", en: "to obey / follow / comply with", heb: "לציית / לעקוב אחרי", cat: "UNIT2_KANJI", ex: "ルールに従う。", exHeb: "לציית לכללים.", kanjiStory: "従(follow) = walking behind someone obediently" },
  { jp: "服従する（ふくじゅうする）", en: "to submit / obey completely", heb: "להיכנע / לציית לחלוטין", cat: "UNIT2_KANJI", ex: "権力に服従する。", exHeb: "להיכנע לשלטון.", kanjiStory: "服(obey) + 従(follow) = obey and follow completely" },
  { jp: "主従関係（しゅじゅうかんけい）", en: "master-servant relationship", heb: "יחסי אדון-משרת", cat: "UNIT2_KANJI", ex: "主従関係が厳しい時代だった。", exHeb: "זו הייתה תקופה עם יחסי אדון-משרת קשים.", kanjiStory: "主(master) + 従(servant) + 関係(relation) = master-servant relation" },
  { jp: "対処する（たいしょする）", en: "to deal with / handle / cope", heb: "להתמודד עם", cat: "UNIT2_KANJI", ex: "問題に対処する。", exHeb: "להתמודד עם הבעיה.", kanjiStory: "対(against) + 処(deal) = dealing against a problem" },
  { jp: "対処法（たいしょほう）", en: "coping method / countermeasure", heb: "שיטת התמודדות", cat: "UNIT2_KANJI", ex: "ストレスの対処法を学ぶ。", exHeb: "ללמוד שיטות התמודדות עם לחץ.", kanjiStory: "対処(cope) + 法(method) = method of coping" },
  { jp: "処方箋（しょほうせん）", en: "prescription (medical)", heb: "מרשם רפואי", cat: "UNIT2_KANJI", ex: "医者に処方箋をもらった。", exHeb: "קיבלתי מרשם מהרופא.", kanjiStory: "処(deal) + 方(method) + 箋(slip) = a slip with the method of treatment" },
  { jp: "意識する（いしきする）", en: "to be conscious / aware of", heb: "להיות מודע ל", cat: "UNIT2_KANJI", ex: "健康を意識する。", exHeb: "להיות מודע לבריאות.", kanjiStory: "意(mind) + 識(know) = mind knows → conscious" },
  { jp: "認識する（にんしきする）", en: "to recognize / acknowledge", heb: "להכיר / להבחין", cat: "UNIT2_KANJI", ex: "問題を認識する。", exHeb: "להכיר בבעיה.", kanjiStory: "認(acknowledge) + 識(know) = acknowledge and know" },
  { jp: "装う（よそおう）", en: "to pretend / disguise / dress up", heb: "להעמיד פנים / להתחפש", cat: "UNIT2_KANJI", ex: "平気を装う。", exHeb: "להעמיד פנים שהכל בסדר.", kanjiStory: "装(wear) = wearing a mask to pretend" },
  { jp: "服装（ふくそう）", en: "attire / clothing / outfit", heb: "לבוש / הלבשה", cat: "UNIT2_KANJI", ex: "服装に気をつける。", exHeb: "להקפיד על הלבוש.", kanjiStory: "服(clothes) + 装(wear) = what you wear" },
  { jp: "装飾品（そうしょくひん）", en: "ornament / accessory / decoration", heb: "תכשיט / אביזר נוי", cat: "UNIT2_KANJI", ex: "高い装飾品を買った。", exHeb: "קניתי תכשיט יקר.", kanjiStory: "装(adorn) + 飾(decorate) + 品(item) = item for decoration" },
  { jp: "突く（つく）", en: "to poke / thrust / stab", heb: "לדקור / לדחוף", cat: "UNIT2_KANJI", ex: "指で突く。", exHeb: "לדקור באצבע.", kanjiStory: "突(thrust) = thrusting forward suddenly" },
  { jp: "突然（とつぜん）", en: "suddenly / all of a sudden", heb: "פתאום / לפתע", cat: "UNIT2_KANJI", ex: "突然雨が降り出した。", exHeb: "פתאום התחיל לרדת גשם.", kanjiStory: "突(sudden) + 然(manner) = in a sudden manner" },
  { jp: "突出する（とっしゅつする）", en: "to protrude / stand out", heb: "לבלוט / להתבלט", cat: "UNIT2_KANJI", ex: "彼の成績は突出している。", exHeb: "הציונים שלו בולטים מעל כולם.", kanjiStory: "突(thrust) + 出(out) = thrusting out above others" },
  { jp: "希望する（きぼうする）", en: "to hope / wish for", heb: "לקוות / לייחל", cat: "UNIT2_KANJI", ex: "転職を希望する。", exHeb: "מקווה להחליף עבודה.", kanjiStory: "希(rare) + 望(wish) = wishing for something rare" },
  { jp: "希少な（きしょうな）", en: "rare / scarce / precious", heb: "נדיר / יקר מציאות", cat: "UNIT2_KANJI", ex: "希少な動物を保護する。", exHeb: "להגן על חיות נדירות.", kanjiStory: "希(rare) + 少(few) = rare and few" },
  { jp: "逆に（ぎゃくに）", en: "conversely / on the contrary", heb: "להפך / ההיפך", cat: "UNIT2_KANJI", ex: "逆に考えてみよう。", exHeb: "בוא נחשוב על זה הפוך.", kanjiStory: "逆(reverse) = flipping to the reverse side" },
  { jp: "反逆する（はんぎゃくする）", en: "to rebel / revolt against", heb: "למרוד / להתמרד", cat: "UNIT2_KANJI", ex: "王に反逆する。", exHeb: "למרוד במלך.", kanjiStory: "反(anti) + 逆(reverse) = going against and reversing" },
  { jp: "逆行する（ぎゃっこうする）", en: "to go against / regress / run counter", heb: "לנוע בכיוון ההפוך / לסגת", cat: "UNIT2_KANJI", ex: "時代に逆行する考え方。", exHeb: "חשיבה שנוגדת את הזמנים.", kanjiStory: "逆(reverse) + 行(go) = going in reverse" },
  { jp: "版（はん/ばん）", en: "edition / version / printing plate", heb: "מהדורה / גרסה", cat: "UNIT2_KANJI", ex: "新しい版が出た。", exHeb: "יצאה מהדורה חדשה.", kanjiStory: "版(plate) = a printing plate that stamps out editions" },
  { jp: "生徒（せいと）", en: "student / pupil", heb: "תלמיד", cat: "UNIT2_KANJI", ex: "生徒が質問した。", exHeb: "תלמיד שאל שאלה.", kanjiStory: "生(life) + 徒(follower) = follower learning about life" },
  { jp: "教徒（きょうと）", en: "believer / follower (religion)", heb: "מאמין (דתי)", cat: "UNIT2_KANJI", ex: "キリスト教徒が多い。", exHeb: "יש הרבה נוצרים.", kanjiStory: "教(teach) + 徒(follower) = follower of teachings" },
  { jp: "徒労（とろう）", en: "futile effort / wasted labor", heb: "מאמץ לשווא", cat: "UNIT2_KANJI", ex: "徒労に終わった。", exHeb: "זה הסתיים כמאמץ לשווא.", kanjiStory: "徒(empty) + 労(labor) = empty labor" },
  { jp: "仮に（かりに）", en: "supposing / if hypothetically", heb: "בהנחה ש / אילו", cat: "UNIT2_KANJI", ex: "仮にお金があったら何をする？", exHeb: "אילו היה לך כסף, מה היית עושה?", kanjiStory: "仮(temporary) = temporarily assuming something" },
  { jp: "仮定（かてい）", en: "assumption / supposition", heb: "הנחה / הנחת יסוד", cat: "UNIT2_KANJI", ex: "仮定の話をする。", exHeb: "לדבר על הנחות.", kanjiStory: "仮(temporary) + 定(fix) = temporarily fixing an assumption" },
  { jp: "仮説（かせつ）", en: "hypothesis / theory", heb: "השערה / תאוריה", cat: "UNIT2_KANJI", ex: "仮説を立てる。", exHeb: "להעלות השערה.", kanjiStory: "仮(temporary) + 説(theory) = temporary theory to test" },
  { jp: "略（りゃく）", en: "abbreviation / omission", heb: "קיצור / השמטה", cat: "UNIT2_KANJI", ex: "略して「AI」と呼ぶ。", exHeb: "בקיצור קוראים לזה AI.", kanjiStory: "略(abbreviate) = cutting short to save time" },
  { jp: "省略する（しょうりゃくする）", en: "to omit / abbreviate / skip", heb: "להשמיט / לקצר", cat: "UNIT2_KANJI", ex: "説明を省略する。", exHeb: "להשמיט את ההסבר.", kanjiStory: "省(save) + 略(abbreviate) = save by abbreviating" },
  { jp: "養う（やしなう）", en: "to nurture / support / foster", heb: "לטפח / לפרנס", cat: "UNIT2_KANJI", ex: "家族を養う。", exHeb: "לפרנס את המשפחה.", kanjiStory: "養(nurture) = feeding and nurturing to grow" },
  { jp: "教養（きょうよう）", en: "culture / education / refinement", heb: "תרבות / השכלה כללית", cat: "UNIT2_KANJI", ex: "教養がある人。", exHeb: "אדם בעל השכלה.", kanjiStory: "教(teach) + 養(nurture) = teaching that nurtures the mind" },
  { jp: "養子（ようし）", en: "adopted child", heb: "ילד מאומץ", cat: "UNIT2_KANJI", ex: "養子を迎える。", exHeb: "לאמץ ילד.", kanjiStory: "養(nurture) + 子(child) = child you chose to nurture" },
  { jp: "平均（へいきん）", en: "average / mean", heb: "ממוצע", cat: "UNIT2_KANJI", ex: "平均点は70点だ。", exHeb: "הציון הממוצע הוא 70.", kanjiStory: "平(flat) + 均(equal) = flat and equal → average" },
  { jp: "均一（きんいつ）", en: "uniform / equal / consistent", heb: "אחיד / שווה", cat: "UNIT2_KANJI", ex: "品質を均一にする。", exHeb: "להפוך את האיכות לאחידה.", kanjiStory: "均(equal) + 一(one) = equal as one" },
  { jp: "興味（きょうみ）", en: "interest / curiosity", heb: "עניין / סקרנות", cat: "UNIT2_KANJI", ex: "日本語に興味がある。", exHeb: "יש לי עניין ביפנית.", kanjiStory: "興(excitement) + 味(flavor) = the flavor of excitement" },
  { jp: "興奮（こうふん）", en: "excitement / agitation", heb: "התרגשות / סערת רגשות", cat: "UNIT2_KANJI", ex: "興奮して眠れなかった。", exHeb: "הייתי כל כך נרגש שלא יכולתי לישון.", kanjiStory: "興(excite) + 奮(rouse) = excitement rousing you up" },
  { jp: "群れ（むれ）", en: "flock / herd / group / swarm", heb: "עדר / להקה / קבוצה", cat: "UNIT2_KANJI", ex: "鳥の群れが飛んでいる。", exHeb: "להקת ציפורים עפה.", kanjiStory: "群(group) = sheep gathering in a group" },
  { jp: "項目群（こうもくぐん）", en: "group of items / item cluster", heb: "קבוצת פריטים", cat: "UNIT2_KANJI", ex: "関連する項目群をまとめる。", exHeb: "לרכז קבוצת פריטים קשורים.", kanjiStory: "項目(item) + 群(group) = items grouped together" },
  { jp: "測る（はかる）", en: "to measure / gauge", heb: "למדוד", cat: "UNIT2_KANJI", ex: "温度を測る。", exHeb: "למדוד את הטמפרטורה.", kanjiStory: "測(measure) = using water to measure depth" },
  { jp: "測定する（そくていする）", en: "to measure / determine precisely", heb: "למדוד / לקבוע במדויק", cat: "UNIT2_KANJI", ex: "データを測定する。", exHeb: "למדוד נתונים.", kanjiStory: "測(measure) + 定(fix) = measure and fix a value" },
  { jp: "亡くなる（なくなる）", en: "to pass away (euphemism)", heb: "נפטר / הלך לעולמו", cat: "UNIT2_KANJI", ex: "祖父が亡くなった。", exHeb: "סבא שלי נפטר.", kanjiStory: "亡(perish) = someone who is no longer here" },
  { jp: "死亡する（しぼうする）", en: "to die (formal / medical)", heb: "למות (רשמי / רפואי)", cat: "UNIT2_KANJI", ex: "事故で3人が死亡した。", exHeb: "שלושה אנשים מתו בתאונה.", kanjiStory: "死(death) + 亡(perish) = death and perishing" },
  { jp: "著しい（いちじるしい）", en: "remarkable / significant / striking", heb: "ניכר / בולט / משמעותי", cat: "UNIT2_KANJI", ex: "著しい成長を遂げた。", exHeb: "השיג צמיחה משמעותית.", kanjiStory: "著(remark) = so notable it must be written down" },
  { jp: "著者（ちょしゃ）", en: "author / writer", heb: "מחבר / סופר", cat: "UNIT2_KANJI", ex: "この本の著者は有名だ。", exHeb: "המחבר של הספר הזה מפורסם.", kanjiStory: "著(write) + 者(person) = person who writes" },
  { jp: "著名（ちょめい）", en: "famous / renowned / distinguished", heb: "מפורסם / ידוע שם", cat: "UNIT2_KANJI", ex: "著名な科学者。", exHeb: "מדען מפורסם.", kanjiStory: "著(notable) + 名(name) = notable name → famous" },
  // UNIT2 VOCAB
  { jp: "囲む（かこむ）", en: "to surround / enclose", heb: "להקיף / לסגור על", cat: "UNIT2_VOCAB", ex: "テーブルを囲む。", exHeb: "לשבת מסביב לשולחן.", kanjiStory: "囲(surround) = walls closing in around something" },
  { jp: "達する（たっする）", en: "to reach / attain / arrive at", heb: "להגיע ל / להשיג", cat: "UNIT2_VOCAB", ex: "目標に達する。", exHeb: "להגיע ליעד.", kanjiStory: "達(reach) = reaching out far enough to arrive" },
  { jp: "装う（よそおう）", en: "to pretend / feign / dress up", heb: "להעמיד פנים / להתלבש", cat: "UNIT2_VOCAB", ex: "知らないふりを装う。", exHeb: "להעמיד פנים שלא יודע.", kanjiStory: "装(wear) = putting on a disguise" },
  { jp: "躍起になる（やっきになる）", en: "to become frantic / desperate", heb: "להיכנס לטירוף / נואש", cat: "UNIT2_VOCAB", ex: "合格しようと躍起になる。", exHeb: "נכנס לטירוף כדי לעבור.", kanjiStory: "躍(leap) + 起(rise) = leaping up in desperation" },
  { jp: "従う（したがう）", en: "to obey / follow / comply", heb: "לציית / לעקוב", cat: "UNIT2_VOCAB", ex: "先生の指示に従う。", exHeb: "לציית להוראות המורה.", kanjiStory: "従(follow) = following behind obediently" },
  { jp: "亡くなる（なくなる）", en: "to pass away (polite)", heb: "נפטר", cat: "UNIT2_VOCAB", ex: "友人のお父さんが亡くなった。", exHeb: "אביו של חבר שלי נפטר.", kanjiStory: "亡(perish) = gone from this world" },
  { jp: "味方（みかた）", en: "ally / supporter / on one's side", heb: "בן ברית / תומך", cat: "UNIT2_VOCAB", ex: "私はあなたの味方だ。", exHeb: "אני בצד שלך.", kanjiStory: "味(taste) + 方(person) = person on your flavor → your side" },
  { jp: "ジョーク", en: "joke / gag", heb: "בדיחה", cat: "UNIT2_VOCAB", ex: "ジョークを言って笑わせた。", exHeb: "סיפר בדיחה וגרם לכולם לצחוק." },
  { jp: "人並み（ひとなみ）", en: "average / ordinary / normal", heb: "ממוצע / רגיל", cat: "UNIT2_VOCAB", ex: "人並みの生活がしたい。", exHeb: "רוצה לחיות חיים רגילים.", kanjiStory: "人(person) + 並(lined up) = lined up with everyone → average" },
  { jp: "悪口（わるくち）", en: "badmouthing / slander / trash talk", heb: "לשון הרע / רכילות", cat: "UNIT2_VOCAB", ex: "人の悪口を言うな。", exHeb: "אל תדבר לשון הרע על אנשים.", kanjiStory: "悪(bad) + 口(mouth) = bad mouth" },
  { jp: "家柄（いえがら）", en: "family background / lineage", heb: "מוצא משפחתי / ייחוס", cat: "UNIT2_VOCAB", ex: "家柄がいい。", exHeb: "בעל מוצא משפחתי טוב.", kanjiStory: "家(house) + 柄(pattern) = the pattern of your house → lineage" },
  { jp: "仮説（かせつ）", en: "hypothesis / theory", heb: "השערה", cat: "UNIT2_VOCAB", ex: "仮説を検証する。", exHeb: "לאמת השערה.", kanjiStory: "仮(temporary) + 説(theory) = temporary theory" },
  { jp: "無駄（むだ）", en: "waste / futility / useless", heb: "בזבוז / לשווא", cat: "UNIT2_VOCAB", ex: "時間を無駄にするな。", exHeb: "אל תבזבז זמן.", kanjiStory: "無(without) + 駄(value) = without value → waste" },
  { jp: "めったにない", en: "rarely / seldom / hardly ever", heb: "נדיר / כמעט אף פעם", cat: "UNIT2_VOCAB", ex: "こんなチャンスはめったにない。", exHeb: "הזדמנות כזו נדירה." },
  { jp: "いったい", en: "on earth / what the (emphasis)", heb: "בכלל / לעזאזל (הדגשה)", cat: "UNIT2_VOCAB", ex: "いったい何が起きたの？", exHeb: "מה לעזאזל קרה?" },
  { jp: "おそらく", en: "probably / most likely", heb: "כנראה / ככל הנראה", cat: "UNIT2_VOCAB", ex: "おそらく彼は来ないだろう。", exHeb: "כנראה שהוא לא יגיע." },
  { jp: "あまりに", en: "excessively / too much", heb: "יותר מדי / מוגזם", cat: "UNIT2_VOCAB", ex: "あまりに高い。", exHeb: "יקר מדי." },
  { jp: "逆に（ぎゃくに）", en: "conversely / on the contrary / instead", heb: "להפך / דווקא ההיפך", cat: "UNIT2_VOCAB", ex: "逆に、彼のほうが悪い。", exHeb: "להפך, דווקא הוא האשם.", kanjiStory: "逆(reverse) = flipping the perspective" },
  // MY SAVED WORDS
  { jp: "獅子の子落とし（ししのこおとし）", en: "throw into hardship to toughen up", heb: "לזרוק למים עמוקים", cat: "MY_WORDS", ex: "獅子の子落としの教育方針。", exHeb: "גישה חינוכית של זריקה למים עמוקים." },
  { jp: "後ろめたい（うしろめたい）", en: "guilty feeling / conscience-stricken", heb: "תחושת אשמה", cat: "MY_WORDS", ex: "嘘をついて後ろめたい。", exHeb: "מרגיש אשמה כי שיקרתי.", kanjiStory: "後ろ(behind) = guilt biting from behind" },
  { jp: "くもの子を散らす", en: "scatter in panic (like spider babies)", heb: "להתפזר בבהלה", cat: "MY_WORDS", ex: "警察が来て、くもの子を散らすように逃げた。", exHeb: "המשטרה הגיעה וכולם התפזרו בבהלה." },
  { jp: "自業自得（じごうじとく）", en: "you reap what you sow / deserved it", heb: "מגיע לך / קארמה", cat: "MY_WORDS", ex: "勉強しなかったから不合格。自業自得だ。", exHeb: "לא למדתי ונכשלתי. מגיע לי.", kanjiStory: "自(self) + 業(deed) + 自(self) + 得(gain) = your own deeds, your own gains" },
  { jp: "老害（ろうがい）", en: "toxic old people blocking progress", heb: "זקנים שחוסמים התקדמות", cat: "MY_WORDS", ex: "あの上司は老害だ。", exHeb: "הבוס ההוא זקן שחוסם התקדמות.", kanjiStory: "老(old) + 害(harm) = old people causing harm" },
  { jp: "会釈（えしゃく）", en: "slight bow (casual greeting)", heb: "הנהון קל (ברכה)", cat: "MY_WORDS", ex: "すれ違うときに会釈した。", exHeb: "הנהנתי כשעברתי לידו.", kanjiStory: "会(meet) + 釈(interpret) = brief meeting greeting" },
  { jp: "尽力いたします（じんりょく）", en: "I will do my utmost (humble)", heb: "אעשה כמיטב יכולתי", cat: "MY_WORDS", ex: "プロジェクトに尽力いたします。", exHeb: "אעשה כמיטב יכולתי בפרויקט.", kanjiStory: "尽(exhaust) + 力(power) = exhaust all power" },
  { jp: "従来は（じゅうらいは）", en: "until now / traditionally", heb: "עד עכשיו / באופן מסורתי", cat: "MY_WORDS", ex: "従来は紙でやっていた。", exHeb: "עד עכשיו עשו את זה על נייר.", kanjiStory: "従(follow) + 来(come) = following what came before" },
  { jp: "反芻（はんすう）", en: "rumination / thoughts on loop", heb: "מחשבות שחוזרות בלופ", cat: "MY_WORDS", ex: "失敗を反芻してしまう。", exHeb: "מוצא עצמי חוזר על הכישלון בראש.", kanjiStory: "反(repeat) + 芻(chew) = chewing again" },
  { jp: "怠惰（たいだ）", en: "laziness / sloth", heb: "עצלנות", cat: "MY_WORDS", ex: "怠惰な生活を送っている。", exHeb: "חי חיים של עצלנות.", kanjiStory: "怠(lazy) + 惰(slack) = lazy and slack" },
  { jp: "浮かない顔（うかないかお）", en: "looking depressed / gloomy face", heb: "פרצוף מדוכא", cat: "MY_WORDS", ex: "浮かない顔をしているね。", exHeb: "אתה נראה מדוכא.", kanjiStory: "浮(float) + 顔(face) = a face that won't float up" },
  { jp: "雑談（ざつだん）", en: "small talk / casual chat", heb: "שיחת חולין", cat: "MY_WORDS", ex: "同僚と雑談する。", exHeb: "מפטפט עם עמיתים לעבודה.", kanjiStory: "雑(misc) + 談(talk) = miscellaneous talk" },
  { jp: "不採用（ふさいよう）", en: "job rejection / not hired", heb: "דחייה מעבודה", cat: "MY_WORDS", ex: "不採用の通知が来た。", exHeb: "קיבלתי הודעת דחייה מעבודה.", kanjiStory: "不(not) + 採(pick) + 用(use) = not picked for use" },
  { jp: "勝ち目はない（かちめ）", en: "no chance of winning", heb: "אין סיכוי לנצח", cat: "MY_WORDS", ex: "彼には勝ち目はない。", exHeb: "אין לו סיכוי לנצח.", kanjiStory: "勝(win) + 目(eye) = no eye for victory" },
  { jp: "時代遅れ（じだいおくれ）", en: "outdated / behind the times", heb: "מיושן", cat: "MY_WORDS", ex: "その考えは時代遅れだ。", exHeb: "החשיבה הזו מיושנת.", kanjiStory: "時(time) + 代(era) + 遅(late) = late for the era" },
  { jp: "不可欠（ふかけつ）", en: "indispensable / absolutely essential", heb: "הכרחי / חיוני", cat: "MY_WORDS", ex: "睡眠は不可欠だ。", exHeb: "שינה היא הכרחית.", kanjiStory: "不(not) + 可(possible) + 欠(lack) = impossible to lack" },
  { jp: "のではあるまいか", en: "I suspect / it seems likely that", heb: "ככל הנראה / חושד ש", cat: "MY_WORDS", ex: "彼は来ないのではあるまいか。", exHeb: "חושד שהוא לא יגיע." },
  { jp: "睡魔（すいま）", en: "overwhelming drowsiness", heb: "עייפות מוחצת", cat: "MY_WORDS", ex: "睡魔に襲われた。", exHeb: "העייפות תקפה אותי.", kanjiStory: "睡(sleep) + 魔(demon) = sleep demon" },
  { jp: "暴走族（ぼうそうぞく）", en: "motorcycle gang / delinquents", heb: "כנופיית אופנועים", cat: "MY_WORDS", ex: "暴走族がうるさい。", exHeb: "כנופיית האופנועים רועשת.", kanjiStory: "暴(violent) + 走(run) + 族(clan) = violent running clan" },
  { jp: "詐欺師（さぎし）", en: "con artist / scammer / fraud", heb: "נוכל / רמאי", cat: "MY_WORDS", ex: "あいつは詐欺師だ。", exHeb: "הוא נוכל.", kanjiStory: "詐(deceive) + 欺(cheat) + 師(master) = master of deception" },
  { jp: "違法駐車（いほうちゅうしゃ）", en: "illegal parking", heb: "חניה לא חוקית", cat: "MY_WORDS", ex: "違法駐車で罰金を取られた。", exHeb: "קיבלתי קנס על חניה לא חוקית.", kanjiStory: "違(against) + 法(law) + 駐(park) + 車(car) = car parked against the law" },
  { jp: "倒産する（とうさん）", en: "to go bankrupt / company failure", heb: "לפשוט רגל", cat: "MY_WORDS", ex: "会社が倒産した。", exHeb: "החברה פשטה רגל.", kanjiStory: "倒(topple) + 産(produce) = production topples" },
  { jp: "謳歌する（おうかする）", en: "to enjoy / savor / revel in", heb: "ליהנות מ / לחגוג", cat: "MY_WORDS", ex: "青春を謳歌する。", exHeb: "ליהנות מתקופת הנעורים.", kanjiStory: "謳(sing) + 歌(song) = singing songs" },
  { jp: "黙殺（もくさつ）", en: "to ignore / kill with silence", heb: "להתעלם לחלוטין", cat: "MY_WORDS", ex: "提案を黙殺された。", exHeb: "ההצעה שלי הושתקה.", kanjiStory: "黙(silence) + 殺(kill) = kill with silence" },
  { jp: "極端に（きょくたんに）", en: "to the extreme / drastically", heb: "באופן קיצוני", cat: "MY_WORDS", ex: "極端に寒い。", exHeb: "קר באופן קיצוני.", kanjiStory: "極(extreme) + 端(edge) = at the extreme edge" },
  { jp: "止むを得ない（やむをえない）", en: "unavoidable / no other choice", heb: "אין ברירה / בלית ברירה", cat: "MY_WORDS", ex: "止むを得ない事情がある。", exHeb: "יש נסיבות שאין ברירה.", kanjiStory: "止(stop) + 得(obtain) = cannot obtain a stop → unavoidable" },
  { jp: "挫折（ざせつ）", en: "setback / failure / giving up", heb: "כישלון / נסיגה", cat: "MY_WORDS", ex: "何度も挫折した。", exHeb: "נכשלתי שוב ושוב.", kanjiStory: "挫(crush) + 折(break) = crushed and broken" },
  { jp: "無能（むのう）", en: "incompetent / useless", heb: "חסר יכולת / חסר תועלת", cat: "MY_WORDS", ex: "無能な上司。", exHeb: "בוס חסר יכולת.", kanjiStory: "無(without) + 能(ability) = without ability" },
  { jp: "奪還（だっかん）", en: "recapture / take back by force", heb: "להשיב בכוח / לכבוש מחדש", cat: "MY_WORDS", ex: "領土を奪還する。", exHeb: "להשיב שטח בכוח.", kanjiStory: "奪(seize) + 還(return) = seize it back" },
  { jp: "傀儡師（かいらいし）", en: "puppet master / behind the scenes", heb: "מניע חוטים / בובנאי", cat: "MY_WORDS", ex: "彼は政界の傀儡師だ。", exHeb: "הוא מניע החוטים בפוליטיקה.", kanjiStory: "傀儡(puppet) + 師(master) = puppet master" },
  { jp: "ぼったくり", en: "rip-off / overcharging scam", heb: "עושק / גזל", cat: "MY_WORDS", ex: "あの店はぼったくりだ。", exHeb: "החנות הזו גוזלת." },
  { jp: "ぎこちない", en: "awkward / stiff / clumsy", heb: "מגושם / לא טבעי", cat: "MY_WORDS", ex: "ぎこちない動き。", exHeb: "תנועה מגושמת." },
  { jp: "上がり症（あがりしょう）", en: "performance anxiety / stage fright", heb: "חרדת ביצוע / פחד במה", cat: "MY_WORDS", ex: "上がり症で面接が苦手だ。", exHeb: "בגלל חרדת ביצוע, קשה לי בראיונות.", kanjiStory: "上がり(rise) + 症(condition) = anxiety rises up" },
  { jp: "立て込んで（たてこんで）", en: "swamped / very busy", heb: "עמוס / טרוד", cat: "MY_WORDS", ex: "今、立て込んでいます。", exHeb: "אני עמוס עכשיו.", kanjiStory: "立(stand) + 込(packed) = tasks standing packed together" },
  { jp: "を見据えて（みすえて）", en: "with X in mind / looking ahead to", heb: "עם מבט קדימה ל", cat: "MY_WORDS", ex: "将来を見据えて勉強する。", exHeb: "לומד עם מבט קדימה לעתיד.", kanjiStory: "見(look) + 据(fix) = fixing your gaze on the future" },
  { jp: "深酒（ふかざけ）", en: "heavy drinking / binge drinking", heb: "שתייה מוגזמת", cat: "MY_WORDS", ex: "深酒はやめたほうがいい。", exHeb: "עדיף להפסיק לשתות יותר מדי.", kanjiStory: "深(deep) + 酒(sake) = deep into sake" },
  { jp: "朝礼（ちょうれい）", en: "morning assembly (company)", heb: "מסדר בוקר (חברה)", cat: "MY_WORDS", ex: "毎朝、朝礼がある。", exHeb: "כל בוקר יש מסדר בוקר.", kanjiStory: "朝(morning) + 礼(ceremony) = morning ceremony" },
  { jp: "長閑な（のどかな）", en: "tranquil / peaceful / idyllic", heb: "שליו / אידילי", cat: "MY_WORDS", ex: "長閑な田舎の風景。", exHeb: "נוף כפרי שליו.", kanjiStory: "長(long) + 閑(quiet) = long peaceful quiet" },
  { jp: "人付き合い（ひとづきあい）", en: "socializing / interpersonal relations", heb: "יחסי אנוש / חברתיות", cat: "MY_WORDS", ex: "人付き合いが苦手だ。", exHeb: "קשה לי עם יחסים חברתיים.", kanjiStory: "人(person) + 付(attach) + 合(meet) = people meeting and attaching" },
  { jp: "中途採用（ちゅうとさいよう）", en: "mid-career recruitment / hiring", heb: "גיוס באמצע קריירה", cat: "MY_WORDS", ex: "中途採用で入社した。", exHeb: "התקבלתי לחברה בגיוס אמצע קריירה.", kanjiStory: "中(middle) + 途(path) + 採(pick) + 用(use) = picked for use mid-path" },
  { jp: "内気な（うちきな）", en: "introverted / shy / reserved", heb: "ביישן / מופנם", cat: "MY_WORDS", ex: "内気な性格。", exHeb: "אופי ביישן.", kanjiStory: "内(inside) + 気(spirit) = spirit stays inside" },
  { jp: "もどかしい", en: "frustrating (can't act/express)", heb: "מתסכל (לא יכול לפעול)", cat: "MY_WORDS", ex: "言いたいことが言えなくてもどかしい。", exHeb: "מתסכל שאני לא יכול לומר מה שרוצה." },
  { jp: "欲深い（よくぶかい）", en: "greedy / avaricious", heb: "חמדן / תאב בצע", cat: "MY_WORDS", ex: "欲深い人間。", exHeb: "אדם חמדן.", kanjiStory: "欲(desire) + 深(deep) = desire runs deep" },
  { jp: "なおさら", en: "all the more / even more so", heb: "על אחת כמה וכמה", cat: "MY_WORDS", ex: "雨ならなおさら行きたくない。", exHeb: "אם יורד גשם, על אחת כמה וכמה לא רוצה ללכת." },
  { jp: "滑舌が悪い（かつぜつ）", en: "poor articulation / unclear speech", heb: "דיקציה גרועה", cat: "MY_WORDS", ex: "滑舌が悪くてすみません。", exHeb: "סליחה על הדיקציה הגרועה שלי.", kanjiStory: "滑(smooth) + 舌(tongue) = tongue not smooth" },
  { jp: "だらしない", en: "sloppy / undisciplined / slovenly", heb: "מרושל / לא מסודר", cat: "MY_WORDS", ex: "だらしない格好。", exHeb: "לבוש מרושל." },
  { jp: "人脈形成（じんみゃくけいせい）", en: "networking / building connections", heb: "בניית קשרים מקצועיים", cat: "MY_WORDS", ex: "人脈形成が大切だ。", exHeb: "בניית קשרים מקצועיים חשובה.", kanjiStory: "人(person) + 脈(vein) + 形(shape) + 成(become) = shaping human connections" },
  { jp: "追求（ついきゅう）", en: "pursuit / striving for", heb: "מרדף / שאיפה", cat: "MY_WORDS", ex: "利益を追求する。", exHeb: "לרדוף אחרי רווח.", kanjiStory: "追(chase) + 求(seek) = chase and seek" },
  { jp: "そっけない", en: "cold / blunt / unfriendly", heb: "קר יחס / יבש", cat: "MY_WORDS", ex: "そっけない返事。", exHeb: "תשובה קרה ויבשה." },
  { jp: "毅然と（きぜんと）", en: "firmly / resolutely / with backbone", heb: "בנחישות / בתקיפות", cat: "MY_WORDS", ex: "毅然とした態度。", exHeb: "גישה נחושה ותקיפה.", kanjiStory: "毅(resolute) + 然(manner) = in a resolute manner" },
  { jp: "課題（かだい）", en: "challenge / issue / assignment", heb: "אתגר / בעיה / מטלה", cat: "MY_WORDS", ex: "それは大きな課題だ。", exHeb: "זה אתגר גדול.", kanjiStory: "課(assign) + 題(topic) = assigned topic" },
  { jp: "極めて（きわめて）", en: "extremely (formal/written)", heb: "ביותר (רשמי)", cat: "MY_WORDS", ex: "極めて重要な問題だ。", exHeb: "זו בעיה חשובה ביותר.", kanjiStory: "極(extreme) = pushed to the extreme limit" },
  { jp: "頻繁に（ひんぱんに）", en: "frequently (formal upgrade of よく)", heb: "לעיתים תכופות", cat: "MY_WORDS", ex: "頻繁にステーキ屋に通っている。", exHeb: "הולך למסעדת סטייק לעיתים תכופות.", kanjiStory: "頻(frequent) + 繁(busy) = frequently busy" },
  { jp: "没入する（ぼつにゅう）", en: "to be fully immersed / absorbed", heb: "להיות שקוע לגמרי", cat: "MY_WORDS", ex: "ゲームに没入する。", exHeb: "להיות שקוע לגמרי במשחק.", kanjiStory: "没(sink) + 入(enter) = sink in and enter" },
  { jp: "増量（ぞうりょう）", en: "increase amount / bulk up", heb: "הגדלת כמות / עלייה במשקל", cat: "MY_WORDS", ex: "筋トレで増量中だ。", exHeb: "עולה במשקל בזכות אימוני כוח.", kanjiStory: "増(increase) + 量(amount) = increase the amount" },
  { jp: "活字中毒（かつじちゅうどく）", en: "addiction to printed word / bookworm", heb: "מכור לקריאה", cat: "MY_WORDS", ex: "活字中毒で、毎日本を読む。", exHeb: "אני מכור לקריאה, קורא ספר כל יום.", kanjiStory: "活字(printed type) + 中毒(addiction) = addicted to printed text" },
  { jp: "人柄（ひとがら）", en: "personality / character (of person)", heb: "אופי / אישיות", cat: "MY_WORDS", ex: "彼は人柄がいい。", exHeb: "יש לו אופי טוב.", kanjiStory: "人(person) + 柄(pattern) = a person's pattern → character" },
  { jp: "饒舌な（じょうぜつな）", en: "talkative / chatty / verbose", heb: "פטפטן / דברן", cat: "MY_WORDS", ex: "彼は饒舌な人だ。", exHeb: "הוא אדם פטפטן.", kanjiStory: "饒(abundant) + 舌(tongue) = abundant tongue → talkative" },
  { jp: "至って（いたって）", en: "very much / extremely (calm tone)", heb: "מאוד / לחלוטין", cat: "MY_WORDS", ex: "至って元気です。", exHeb: "אני בריא לחלוטין.", kanjiStory: "至(reach) = reaching the utmost degree" },
  { jp: "棺桶（かんおけ）", en: "coffin / casket", heb: "ארון קבורה", cat: "MY_WORDS", ex: "棺桶に入る年齢だ。", exHeb: "בגיל שכבר רגל אחת בקבר.", kanjiStory: "棺(coffin) + 桶(barrel) = the barrel-shaped coffin" },
  { jp: "頗る（すこぶる）", en: "very / remarkably / exceedingly", heb: "מאוד / להפליא", cat: "MY_WORDS", ex: "頗る調子がいい。", exHeb: "המצב טוב להפליא." },
  { jp: "行きつけ（いきつけ）", en: "regular (place you frequent)", heb: "מקום קבוע / רגיל", cat: "MY_WORDS", ex: "行きつけの居酒屋がある。", exHeb: "יש לי איזקאיה קבועה.", kanjiStory: "行き(go) + つけ(used to) = a place you're used to going" },
  { jp: "居眠り（いねむり）", en: "dozing off / nodding off", heb: "לנמנם / להירדם", cat: "MY_WORDS", ex: "会議中に居眠りした。", exHeb: "נרדמתי באמצע הישיבה.", kanjiStory: "居(sit) + 眠り(sleep) = sleeping while sitting" },
  { jp: "始末だ（しまつだ）", en: "pathetic ending / what a mess", heb: "סוף עלוב / איזה בלגן", cat: "MY_WORDS", ex: "嘘がばれてこの始末だ。", exHeb: "השקר נחשף וזה הסוף העלוב.", kanjiStory: "始(begin) + 末(end) = from start to end → the messy outcome" },
  { jp: "百戦錬磨（ひゃくせんれんま）", en: "battle-hardened veteran / seasoned", heb: "ותיק מנוסה / מחושל קרבות", cat: "MY_WORDS", ex: "百戦錬磨のビジネスマン。", exHeb: "איש עסקים ותיק ומחושל.", kanjiStory: "百(100) + 戦(battle) + 錬(temper) + 磨(polish) = tempered and polished by 100 battles" },
  { jp: "居心地（いごこち）", en: "comfort / how it feels to be there", heb: "נוחות / תחושת שהייה", cat: "MY_WORDS", ex: "このカフェは居心地がいい。", exHeb: "בבית הקפה הזה נעים לשבת.", kanjiStory: "居(stay) + 心(heart) + 地(ground) = the ground where your heart stays" },
  { jp: "パリピ", en: "party people (slang パーティーピーポー)", heb: "אנשי מסיבות", cat: "MY_WORDS", ex: "彼はパリピだから毎週末クラブにいる。", exHeb: "הוא פריק מסיבות, כל סופשבוע במועדון." },
  { jp: "老年医学（ろうねんいがく）", en: "geriatrics / elderly medicine", heb: "רפואת זקנה / גריאטריה", cat: "MY_WORDS", ex: "老年医学を専門にしている。", exHeb: "מתמחה ברפואת זקנה.", kanjiStory: "老(old) + 年(year) + 医(medicine) + 学(study) = study of medicine for the old" },
  { jp: "本音と建前（ほんねとたてまえ）", en: "true feelings vs official stance", heb: "רגשות אמיתיים מול עמדה רשמית", cat: "MY_WORDS", ex: "日本は本音と建前の文化がある。", exHeb: "ביפן יש תרבות של פנים אמיתיות מול מסכה רשמית.", kanjiStory: "本音(true sound) + 建前(facade) = what you really think vs what you show" },
  { jp: "反出生主義（はんしゅっしょうしゅぎ）", en: "antinatalism", heb: "אנטי-נטליזם / נגד הולדה", cat: "MY_WORDS", ex: "反出生主義の哲学者。", exHeb: "פילוסוף אנטי-נטליסט.", kanjiStory: "反(anti) + 出生(birth) + 主義(ism) = anti-birth ideology" },
  { jp: "裏金（うらがね）", en: "dirty money / slush fund / bribe", heb: "כסף מלוכלך / שוחד", cat: "MY_WORDS", ex: "裏金問題が発覚した。", exHeb: "פרשת הכסף המלוכלך נחשפה.", kanjiStory: "裏(behind) + 金(money) = money behind the scenes" },
  { jp: "閉鎖（へいさ）", en: "shutdown / closure / lockdown", heb: "סגירה / השבתה", cat: "MY_WORDS", ex: "工場が閉鎖された。", exHeb: "המפעל נסגר.", kanjiStory: "閉(close) + 鎖(chain) = closed and chained shut" },
];

export const PASS_SCORE = 80;
export const QUESTIONS_PER_TEST = 30;
export const TIMER_SECONDS = 15 * 60;
